sp_tickers = [
    "AAPL", "MSFT", "GOOGL", "GOOG", "AMZN", "TSLA", "FB", "BRK.B", "JPM", "JNJ",
    "NVDA", "V", "PG", "MA", "UNH", "PYPL", "HD", "DIS", "BAC", "CMCSA",
    "TMO", "ADBE", "XOM", "CRM", "INTC", "PEP", "VZ", "MRK", "NFLX", "PFE",
    "KO", "ABBV", "T", "CSCO", "ABBV", "CVX", "NKE", "WMT", "COST", "MCD",
    "C", "ABT", "MRNA", "QCOM", "GILD", "TGT", "LOW", "BMY", "HON", "DHR",
    "SBUX", "AVGO", "PM", "ORCL", "IBM", "MS", "UPS", "CHTR", "CAT", "LMT",
    "NEE", "GS", "MMM", "AMGN", "MO", "AMAT", "TXN", "BKNG", "LLY", "ADP",
    "NOW", "ISRG", "ANTM", "TFC", "CVS", "VRTX", "USB", "DUK", "TMUS", "CCI",
    "PLD", "SPGI", "ECL", "GPN", "BLK", "GM", "BDX", "ICE", "SO", "CI", "ETN",
    "FDX", "GD", "LRCX", "EOG", "APD", "SHW", "PNC", "MET", "NSC", "AON",
    "ADSK", "CL", "MMC", "CB", "TROW", "MCO", "EQIX", "TMX", "TDG", "COF",
    "BAX", "SYK", "PSX", "BIIB", "FIS", "ITW", "WM", "DG", "AEP", "FD", "EMR",
    "LHX", "SNP", "AZO", "ROST", "NOC", "AIG", "KR", "ESS", "VRTX", "SCHW",
    "CTSH", "CTAS", "STZ", "FE", "AFL", "WBA", "AMP", "TROW", "SO", "BLL",
    "WELL", "MKC", "EOG", "KMB", "DUK", "AEP", "DTE", "CBRE", "EXC", "BKR",
    "PPL", "WEC", "AWK", "ALLE", "EIX", "VRSN", "D", "WLTW", "UDR", "LDOS",
    "HLT", "FLT", "VTRS", "PXD", "EW", "ATO", "CDW", "PAYC", "FTNT", "OTIS",
    "TDY", "CDNS", "MSCI", "ZBRA", "TWTR", "FTV", "KEYS", "STE", "ANSS", "SNPS",
    "ZTS", "LBRDK", "IQV", "MKTX", "RMD", "MXIM", "CRL", "FRC", "CPRT", "IDXX",
    "JKHY", "AJG", "PEAK", "ESS", "CTXS", "URI", "SWK", "DLR", "VNO", "FAST",
    "LNT", "BR", "AIZ", "ALGN", "UAA", "MLM", "TTWO", "CPB", "CINF", "VFC",
    "KSU", "FTNT", "TDY", "LW", "WAB", "HRL", "AME", "ATO", "HIG", "HBAN",
    "ROL", "ANET", "WRB", "NUE", "UDR", "ARE", "RSG", "FTV", "NVR", "J",
    "MKTX", "FLT", "ABMD", "AKAM", "AVB", "RHI", "SNPS", "ZBRA", "IDXX", "CARR",
    "RE", "LYV", "CBRE", "CMI", "DVA", "LVS", "CTLT", "DXCM", "CERN", "AAL",
    "COG", "SIVB", "KMX", "HST", "NTRS", "CHRW", "ZION", "TPR", "APA", "CBOE",
    "VTR", "DVN", "LH", "NI", "WY", "CMS", "GL", "EXPE", "LYB", "O", "VLO",
    "NCLH", "FFIV", "L", "TDG", "BBWI", "HCA", "UNM", "JNPR", "MAS", "WDC",
    "BKR", "NOV", "CNP", "MGM", "XRX", "PVH", "UHS", "VNT", "APA", "AES",
    "DXC", "GPS", "BRX", "PRGO", "NRG", "RJF", "FLS", "F", "TDG", "HOLX", "PWR",
    "URI", "AAP", "NLOK", "HP", "NWL", "MHK", "VAR", "LEG", "WELL", "COTY",
    "FLR", "ARNC", "FANG", "KEY", "LKQ", "SEE", "FLIR", "HFC", "NRG", "BHF",
    "DISCK", "DISCA", "FMC", "BEN", "PKG", "AJG", "MHK", "IVZ", "CF", "NWSA",
    "NWS", "PBCT", "XRX", "EXR", "WRK", "TAP", "HFC", "DISH", "PKG", "OXY",
    "IVZ", "UA", "DISCK", "DISCA", "NWL", "FOX", "MHK", "HPE", "NOV", "TAP",
    "KSS", "BEN", "EXR", "PBCT", "NWSA", "NWS", "UA", "DISH", "FOX", "OXY",
    "ADS", "KHC", "MOS", "PVH", "DXC", "UA", "NBL", "ADS", "KHC", "PVH", "DXC",
    "MOS", "SYF", "ZBH", "NCLH", "BRX", "MRO", "GPS", "L", "UAA", "FLS", "FLR",
    "RJF", "RJF", "JNPR", "UHS", "HCA", "BBWI", "HP", "NLOK", "AAP", "HOLX",
    "PWR", "ARNC", "COTY", "LEG", "VAR", "MHK", "FANG", "FLIR", "SEE", "LKQ",
    "KEY", "BHF", "FMC", "DISCK", "DISCA", "BEN", "PKG", "IVZ", "CF", "NWSA",
    "NWS", "PBCT", "XRX", "EXR", "WRK", "TAP", "HFC", "DISH", "PKG", "OXY",
    "IVZ", "UA", "FOX", "NWL", "MHK", "HPE", "NOV", "TAP", "KSS", "BEN", "EXR",
    "PBCT", "NWSA", "NWS", "UA", "DISH", "FOX", "OXY", "ADS", "KHC", "MOS",
    "PVH", "DXC", "UA", "NBL", "ADS", "KHC", "PVH", "DXC", "MOS", "SYF", "ZBH",
    "NCLH", "BRX", "MRO", "GPS", "L", "UAA", "FLS", "FLR", "RJF", "JNPR", "UHS",
    "HCA", "BBWI", "HP", "NLOK", "AAP", "HOLX", "PWR", "ARNC", "COTY", "LEG",
    "VAR", "MHK", "FANG", "FLIR", "SEE", "LKQ", "KEY", "BHF", "FMC", "DISCK",
    "DISCA", "BEN", "PKG", "IVZ", "CF", "NWSA", "NWS", "PBCT", "XRX", "EXR",
    "WRK", "TAP", "HFC", "DISH", "PKG", "OXY", "IVZ", "UA", "FOX", "NWL", "MHK",
    "HPE", "NOV", "TAP", "KSS", "BEN", "EXR", "PBCT", "NWSA", "NWS", "UA",
    "DISH", "FOX", "OXY", "ADS", "KHC", "MOS", "PVH", "DXC", "UA", "NBL", "ADS",
    "KHC", "PVH", "DXC", "MOS", "SYF", "ZBH", "NCLH", "BRX", "MRO", "GPS", "L",
    "UAA", "FLS", "FLR", "RJF", "JNPR", "UHS", "HCA", "BBWI", "HP", "NLOK",
    "AAP", "HOLX", "PWR", "ARNC", "COTY", "LEG", "VAR", "MHK", "FANG", "FLIR",
    "SEE", "LKQ", "KEY", "BHF", "FMC", "DISCK", "DISCA", "BEN", "PKG", "IVZ",
    "CF", "NWSA", "NWS", "PBCT", "XRX", "EXR", "WRK", "TAP", "HFC", "DISH",
    "PKG", "OXY", "IVZ", "UA", "FOX", "NWL", "MHK", "HPE", "NOV", "TAP", "KSS",
    "BEN", "EXR", "PBCT", "NWSA", "NWS", "UA", "DISH", "FOX", "OXY", "ADS",
    "KHC", "MOS", "PVH", "DXC", "UA", "NBL", "ADS", "KHC", "PVH", "DXC", "MOS",
    "SYF", "ZBH", "NCLH", "BRX", "MRO", "GPS", "L", "UAA", "FLS", "FLR", "RJF",
    "JNPR", "UHS", "HCA", "BBWI", "HP", "NLOK", "AAP", "HOLX", "PWR", "ARNC",
    "COTY", "LEG", "VAR", "MHK", "FANG", "FLIR", "SEE", "LKQ", "KEY", "BHF",
    "FMC", "DISCK", "DISCA", "BEN", "PKG", "IVZ", "CF", "NWSA", "NWS", "PBCT",
    "XRX", "EXR", "WRK", "TAP", "HFC", "DISH", "PKG", "OXY", "IVZ", "UA", "FOX",
    "NWL", "MHK", "HPE", "NOV", "TAP", "KSS", "BEN", "EXR", "PBCT", "NWSA",
    "NWS", "UA", "DISH", "FOX", "OXY", "ADS", "KHC", "MOS", "PVH", "DXC", "UA",
    "NBL", "ADS", "KHC", "PVH", "DXC", "MOS", "SYF", "ZBH", "NCLH", "BRX",
    "MRO", "GPS", "L", "UAA", "FLS", "FLR", "RJF", "JNPR", "UHS", "HCA", "BBWI",
    "HP", "NLOK", "AAP", "HOLX", "PWR", "ARNC", "COTY", "LEG", "VAR", "MHK",
    "FANG", "FLIR", "SEE", "LKQ", "KEY", "BHF", "FMC", "DISCK", "DISCA", "BEN",
    "PKG", "IVZ", "CF", "NWSA", "NWS", "PBCT", "XRX", "EXR", "WRK", "TAP", "HFC",
    "DISH", "PKG", "OXY", "IVZ", "UA", "FOX", "NWL", "MHK", "HPE", "NOV", "TAP",
    "KSS", "BEN", "EXR", "PBCT"
]
